todo_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from todo_app.views import (
    HomePageView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskCompleteView,
)


app_name="todo_app"

urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/complete/", TaskCompleteView.as_view(), name="task-complete")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo_app.urls", namespace="todo_app")),
]

todo_app/models.py
from django.db import models

class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(
        "Tag", related_name="tasks", blank=True
    )


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}"

todo_app/forms.py
from django import forms

from todo_app.models import Tag, Task


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["name",]


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    content = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 3, 'cols': 40}),
        required=True
    )
    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        required=False
    )

    class Meta:
        model = Task
        fields = ["content", "deadline", "tags"]

todo_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from todo_app.forms import TagForm, TaskForm
from todo_app.models import Task, Tag


class HomePageView(ListView):
    model = Task
    queryset = Task.objects.prefetch_related(
        "tags"
    ).order_by("is_done", "-created_at")
    template_name = "todo_app/index.html"
    context_object_name = "tasks"


class TaskCreateView(CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_app:index")


class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_app:index")


class TaskCompleteView(DetailView):
    def post(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        task.is_done = not task.is_done
        task.save()
        return redirect("todo_app:index")



class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy("todo_app:index")


class TagListView(ListView):
    model = Tag
    template_name = "todo_app/tag_list.html"
    context_object_name = "tags"


class TagCreateView(CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("todo_app:tag-list")


class TagUpdateView(UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("todo_app:tag-list")


class TagDeleteView(DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_app:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  {% block title %}<title>ToDo</title>{% endblock %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
        crossorigin="anonymous">

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">

    <div class="col-sm-2">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>


    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

{#      {% block pagination %}#}
{#<!--        {% include "includes/pagination.html" %}-->#}
{#      {% endblock %}#}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo_app:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo_app:tag-list' %}">Tags</a></li>
</ul>

templates/todo_app/index.html
{% extends "base.html" %}

{% block content %}

  <div class="page-header">
    <h1>TODO list</h1>

    <a class="btn btn-primary"
       href="{% url 'todo_app:task-create' %}"
       role="button">
      Add task
    </a>
  </div>

  <br>

  <div class="tasks-list">
  {% if tasks %}
    {% for task in tasks %}
      <div class="task-item">

        <div class="content-line">
          <strong>{{ task.content }}
            {% if task.is_done %}
              <span style="color:forestgreen">&nbsp;Done</span>
            {% else %}
              <span style="color:red">&nbsp;Not done</span>
            {% endif %}
          </strong>

        <!---complete button-->
        <form action="{% url 'todo_app:task-complete' pk=task.id %}" method="post">
          {% csrf_token %}
          {% if task.is_done %}
            <button type="submit"
               class="btn btn-warning">
              Undo
            </button>
          {% else %}
            <button type="submit"
               class="btn btn-success">
              Complete
            </button>
          {% endif %}
        </form>
        <!---end complete button-->

        </div>
        <br>

        <p><small>
          Created at: {{ task.created_at|date:"M. d, Y, g:i a" }}
          {% if task.deadline %}
            <span style="color: brown">
              &nbsp;Deadline: {{ task.deadline }}</span>
          {% endif %}
        </small></p>

      <div class="tag-line-with-functions">

        {% if task.tags.all %}
          <p class="text-muted">
            Tags:
            {% for tag in task.tags.all %}
              {% for item in tag.name %}{{ item }}{% endfor %}
            {% endfor %}
          </p>
        {% endif %}

        <a href="{% url 'todo_app:task-update' pk=task.id %}">Update</a>
        <a href="{% url 'todo_app:task-delete' pk=task.id %}">&nbsp;Delete</a>

      </div>
      <hr><br>

      </div>
    {% endfor %}
    {% else %}
    <p class="funny-text">U've done all your tasks. Have a rest!</p>
  {% endif %}
  </div>

{% endblock %}

templates/todo_app/tag_form.html
{% extends "base.html" %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_app/tag_list.html
{% extends "base.html" %}

{% block content %}

  <div class="page-header" style="align-content: flex-start">
    <h1>Tags</h1>
    <a
        class="btn btn-primary"
        href="{% url 'todo_app:tag-create' %}"
        role="button">
      Add
    </a>
  </div>

  <div class="tags-table">
  {% if tags %}

      <table class="table">
        <tr>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>

        {% for tag in tags %}
          <tr>
            <td>{{ tag.name }}</td>

            <td>
                <a class="btn btn-secondary"
                    href="{% url 'todo_app:tag-update' pk=tag.id %}">
                  Update
                </a>
            </td>

            <td>
                <form action="{% url 'todo_app:tag-delete' pk=tag.id %}" method="post">
                  {% csrf_token %}
                  <input class="btn btn-secondary" type="submit" value="Delete">
                </form>
            </td>

          </tr>
        {% endfor %}

      </table>

  {% endif %}
  </div>
{% endblock %}

templates/todo_app/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task</h1>

  <p>Are you sure you want to delete task?</p>

  <div style="display: flex; gap: 20px;">
    <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    </form>
    <form action="{% url 'todo_app:index' %}" method="get">
    <input type="submit" value="No" class="btn btn-primary">
    </form>
  </div>
{% endblock %}

templates/todo_app/task_form.html
{% extends "base.html" %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}